### ISSUE TITLE
APT whitelist request for libdiscid0

### ISSUE THREAD

**Issue by phw** [travis-ci/apt-package-whitelist#1022]

**Comment by BanzaiMan** [comment]
Duplicate of #1023.

**Comment by phw** [comment]
@BanzaiMan Something seems to be wrong with travisbot figuring out the package names. The development package is actually not called `libdiscid-dev` but `libdiscid0-dev`, see http://packages.ubuntu.com/precise/libdiscid0-dev 

I have filed a pull request #1053

Thanks for the fast merge and sorry for the duplicate, didn't know travisbot pulls in related packages.
