### ISSUE TITLE
APT whitelist request for libaugeas0

### ISSUE THREAD

**Issue by AlexanderS** [travis-ci/apt-package-whitelist#105]

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229196.

**Comment by AlexanderS** [comment]
I think that occurences of setuid and setgid are somethink like "schema" definitions for external configuration files.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284726.

**Comment by BanzaiMan** [comment]
OK. I'll re-run the test, so that I can get the list of packages.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 augeas-tools libaugeas-dev libaugeas0 augeas-dbg augeas-lenses augeas-doc

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72404957.
