### ISSUE TITLE
APT whitelist request for mpich2

### ISSUE THREAD

**Issue by bsteinb** [travis-ci/apt-package-whitelist#107]
Has support for the MPI-2.2 standard. OpenMPI which is already whitelisted only offers support for MPI-2.1.

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for mpich2. does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229198.

**Comment by bsteinb** [comment]
I do not know what happened there. The package is in the official sources: http://packages.ubuntu.com/source/precise/mpich2.

In the meantime I have figured out that even the MPI-2.2 standard supported by the mpich2 package is not sufficient. I am now building the dependencies from source and caching them. If it is alright with you, we can close this issue.

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for mpich2. does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284731.

**Comment by BanzaiMan** [comment]
I just realized that there was a dot at the end of the title, and that threw off the script. I'll rerun the test shortly.

**Comment by BanzaiMan** [comment]
Actually, #339 asks for the same package, and we have the list.
