### ISSUE TITLE
Apt whitelist request for g++ 4.7 and 4.8

### ISSUE THREAD

**Issue by WildCard65** [travis-ci/apt-package-whitelist#1359]
I would like both requested versions of g++ be whitelisted please(I accidently posted this request in wrong repo issues section originally)

**Comment by sadjad** [comment]
This issue is in the wrong format. Make sure that you format the title exactly as described here: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
(And one package per issue :wink:)

**Comment by WildCard65** [comment]
Technically, it's 1 program but 2 versions requested
