### ISSUE TITLE
APT whitelist request for shunit2

### ISSUE THREAD

**Issue by havenwood** [travis-ci/apt-package-whitelist#1425]
We use [shUnit2](https://shunit2.googlecode.com/svn/trunk/source/2.1/doc/shunit2.html) for unit testing shell scripting (in [chruby](https://github.com/postmodern/chruby) and [ruby-install](https://github.com/postmodern/ruby-install)).

**Comment by BanzaiMan** [comment]
Duplicate of #1371.
