### ISSUE TITLE
APT whitelist request for gmp

### ISSUE THREAD

**Issue by thiloklein** [travis-ci/apt-package-whitelist#1503]
Please whitelist the GNU Multiple Precision Arithmetic Library (GMP) at https://gmplib.org/

**Comment by thiloklein** [comment]
Thanks for the prompt fix -- much appreciated! How long would this change take to become effective?

After restarting the build, I still see:

configure: error: GNU MP not found, or not 4.1.4 or up, see http://gmplib.org

at https://travis-ci.org/thiloklein/matchingMarkets, line 460.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/86631185#L460-L466 shows that the package is available from `debian-sid`, so you'll need to add that APT source.

**Comment by thiloklein** [comment]
Thanks for the prompt reply -- modifying `.travis.yml` as follows works for me:

addons:
  apt:
    sources:
    - debian-sid

I found your documentation at http://docs.travis-ci.com/user/apt/ helpful.

**Comment by BanzaiMan** [comment]
@thiloklein With https://travis-ci.org/thiloklein/matchingMarkets/builds/87529052, you are adding the package source, but not installing any package.

**Comment by thiloklein** [comment]
Thanks very much for the pointers, I noticed this but the revised https://github.com/thiloklein/matchingMarkets/blob/master/.travis.yml still results in the same error. Thanks in advance for any thoughts about what might cause this.

**Comment by BanzaiMan** [comment]
@thiloklein Now you are not installing any package via APT addon at all.
