### ISSUE TITLE
APT whitelist request for libxcb-ewmh1-dev

### ISSUE THREAD

**Issue by ThomasAdam** [travis-ci/apt-package-whitelist#1581]

**Comment by HarveyHunt** [comment]
The incorrect package has been added to the whitelist - ```libxcb-ewmh1-dev``` was [tested by travisbot](https://github.com/travis-ci/apt-whitelist-checker/commit/c1dcaca593914e1f1ad7e3dc747cddafa174cd98), but ```libxcb-ewmh-dev``` was added to the whitelist. This means that builds using ```libxcb-ewmh1-dev``` are [broken](https://travis-ci.org/HarveyHunt/howm/jobs/93010579#L85).

```libxcb-ewmh1-dev``` exists in precise and ```libxcb-ewmh-dev``` only appears in later versions of Ubuntu.
