### ISSUE TITLE
APT whitelist request for python-pygments

### ISSUE THREAD

**Issue by rnewson** [travis-ci/apt-package-whitelist#175]
For Apache CouchDB.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229241.

**Comment by rnewson** [comment]
That appears to be in the lexxer, it's simply a list of PHP functions to recognise and highlight, it's not calling them.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284873.

**Comment by BanzaiMan** [comment]
I think so. I'll re-run the test to get the list of packages defined in the source package.

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 python-pygments python3-pygments python-pygments-doc

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72404965.
