### ISSUE TITLE
could not add apt packages to ubuntu-trusty whitelist

### ISSUE THREAD

**Issue by furushchev** [travis-ci/apt-package-whitelist#1752]
Currently all requests are added to only ubuntu-precise, and I could not found the guideline to add apt packages to ubuntu-trusty whitelist.
How can I add?

**Comment by furushchev** [comment]
Sorry, I don't know you are the maintainer of this repository, but how do you think of this issue?
@BanzaiMan @travisbot

**Comment by BanzaiMan** [comment]
For Trusty, you should use `sudo` to install packages.

**Comment by furushchev** [comment]
@BanzaiMan I see! Thank you for answer!
