### ISSUE TITLE
APT source whitelist request for ppa:ubuntu-wine/ppa

### ISSUE THREAD

**Issue by kenorb** [travis-ci/apt-package-whitelist#1771]
It is in: `ppa:ubuntu-wine/ppa`:

    sudo add-apt-repository -y ppa:ubuntu-wine/ppa

Deb source line:

    deb http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu trusty main
    deb-src http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu trusty main

My previous attempts: #1401, #1768

My issue: https://github.com/travis-ci/travis-ci/issues/5112

**Comment by BanzaiMan** [comment]
Source requests go to https://github.com/travis-ci/apt-source-whitelist. Thanks.

**Comment by kenorb** [comment]
Follow-up: https://github.com/travis-ci/apt-source-whitelist/issues/191
