### ISSUE TITLE
APT whitelist request for libatlas3gf-base

### ISSUE THREAD

**Issue by eupharis** [travis-ci/apt-package-whitelist#1835]

**Comment by eupharis** [comment]
Thanks!

**Comment by amueller** [comment]
Why do I get this:
```
Installing APT Packages (BETA)

Disallowing packages: libatlas3gf-base

```
?

**Comment by eupharis** [comment]
I had the same issue. If you look at the actual PR that resolved this issue the package `libatlas3gf-base` wasn't actually added:

https://github.com/travis-ci/apt-package-whitelist/pull/1858/files

for my purposes just using libatlas3-base caused my tests to pass so I didn't worry about it.
