### ISSUE TITLE
APT whitelist request for liblmdb-dev

### ISSUE THREAD

**Issue by lukeyeager** [travis-ci/apt-package-whitelist#1922]
**This is a `trusty` package** - it doesn't exist on `precise`.

This package is used by these projects:

* https://github.com/BVLC/caffe
* https://github.com/NVIDIA/caffe
* https://github.com/NVIDIA/DIGITS

On `precise`, LMDB [is being built from source](https://github.com/NVIDIA/caffe/blob/v0.13.2/scripts/travis/travis_install.sh#L49-L59) because no package exists. While testing out the `trusty` beta, I expected to be able to add `liblmdb-dev` to apt like this:
```yaml
addons:
  apt:
    packages:
      - liblmdb-dev
```
But I get this error:
```
[0K[33;1mInstalling APT Packages (BETA)[0m
[31;1mDisallowing packages: liblmdb-dev[0m
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```
Please whitelist this package for `trusty` builds. Thanks!

**Comment by BanzaiMan** [comment]
We apologize, but we currently do not accept requests for Trusty. Our Trusty builds can use `sudo`, so please use that instead.

**Comment by lukeyeager** [comment]
> Our Trusty builds can use sudo, so please use that instead.

Oh got it. So just don't use the `apt` addon? Will do, thanks!
