### ISSUE TITLE
APT whitelist request for qtlocation5-dev

### ISSUE THREAD

**Issue by tmpsantos** [travis-ci/apt-package-whitelist#2900]
Needed for testing software using Qt5 and the QtLocation module.

The package is available by default on the Ubuntu Trusty bot.

http://doc.qt.io/qt-5/qtlocation-index.html

**Comment by BanzaiMan** [comment]
Duplicate of #2899.

**Comment by tmpsantos** [comment]
> Duplicate of #2899.

They are not the same package.

**Comment by BanzaiMan** [comment]
If you look at the PRs involved, you will see that they end up adding the same ones.

**Comment by tmpsantos** [comment]
> If you look at the PRs involved, you will see that they end up adding the same ones.

Indeed, missed that. My apologies.
