### ISSUE TITLE
APT whitelist request for libomp-dev

### ISSUE THREAD

**Issue by ppwwyyxx** [travis-ci/apt-package-whitelist#3199]

**Comment by ppwwyyxx** [comment]
what do I need to do to make it effective?
I restart a previously failed [job](https://travis-ci.org/ppwwyyxx/panorama/jobs/143810745) but it still says
"disallowing packages: libomp-dev".

**Comment by BanzaiMan** [comment]
The package is allowed, but not found. https://travis-ci.org/ppwwyyxx/panorama/jobs/143810745#L143

You need to find the source that has it. https://docs.travis-ci.com/user/installing-dependencies#Identifying-the-source-for-a-missing-package

In this particular case (https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/144020916#L634), you see that the source name is `debian-sid`. https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json#L87-L91

**Comment by ppwwyyxx** [comment]
Thanks a lot! However after I added debian-sid to source list, apt-get starts to fetch everything from debian-sid and it seems to cause conflicts: https://travis-ci.org/ppwwyyxx/panorama/jobs/144317721.
Is there a solution to that?

**Comment by BanzaiMan** [comment]
Unfortunately, there isn't. `debian-sid` is known to cause problems. https://github.com/travis-ci/travis-ci/issues/6073
