### ISSUE TITLE
APT whitelist request for libgd-dev

### ISSUE THREAD

**Issue by schmonz** [travis-ci/apt-package-whitelist#3248]
Hi! I'm wanting to do CI for some code that links with the [GD graphics library](https://libgd.github.io). On Ubuntu, that's `libgd-dev`. Could you please whitelist this package?

**Comment by schmonz** [comment]
Thank you for adding this, and I'm sorry to say it didn't work as expected. There's an additional package or packages I hadn't known I needed to request:

```
Package libgd-dev is a virtual package provided by:
  libgd2-xpm-dev 2.0.36~rc1~dfsg-6ubuntu2.2
  libgd2-noxpm-dev 2.0.36~rc1~dfsg-6ubuntu2.2

E: Package 'libgd-dev' has no installation candidate
```

I'm not using XPM, so either or both of `libgd2-{,no}xpm-dev` will do what I need.

I don't know how to find out whether those, in turn, have additional unmet dependencies. In either case, I assume the XPM variant additionally depends on XPM.

**Comment by BanzaiMan** [comment]
It's probably missing an APT source that provides this package. See https://docs.travis-ci.com/user/installing-dependencies#Identifying-the-source-for-a-missing-package.
