### ISSUE TITLE
APT whitelist request for liblcms-dev

### ISSUE THREAD

**Issue by peter-b** [travis-ci/apt-package-whitelist#329]

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for liblcms-dev does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365365.

**Comment by peter-b** [comment]
Superceded by #349.
