### ISSUE TITLE
APT whitelist request for libtiff-dev

### ISSUE THREAD

**Issue by dougthor42** [travis-ci/apt-package-whitelist#331]
APT whitelist request for `libtiff-dev`

Used to build wxPython Phoenix from source. See https://github.com/wxWidgets/Phoenix#prerequisites

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for libtiff-dev does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365363.

**Comment by dougthor42** [comment]
Sorry, my bad. Turns out this is a virtual package and is covered by libtiff4-dev (which is already on the whitelist). So I think this can be closed.

Source: http://packages.ubuntu.com/precise-updates/libtiff-dev

**Comment by BanzaiMan** [comment]
No worries. Thanks for the update!
