### ISSUE TITLE
Cannot install libsodium13

### ISSUE THREAD

**Issue by rugk** [travis-ci/apt-package-whitelist#3342]
I saw that libsodium13 [got whitelisted](https://github.com/travis-ci/apt-package-whitelist/commit/b0da1da0469213c65137978b2257e064a8d1fc45), but in the default - containerized - Travis builds I can neighter install `libsodium`(which is AFAIK a meta-package for libsodium13) nor libsodium13.
libsodium13 claims to not exist and libsodium is disallowed pointing me here.

**Comment by BanzaiMan** [comment]
Most likely you are missing a source that contains the package you need. Please read https://docs.travis-ci.com/user/installing-dependencies#Identifying-the-source-for-a-missing-package.

**Comment by rugk** [comment]
So I found the PR: https://github.com/travis-ci/apt-package-whitelist/pull/961
And here the build: https://travis-ci.org/travis-ci/apt-package-whitelist/jobs/76913500

But in the build nearly nothing is done. I can also see no "Fetching source package for …".

**Comment by BanzaiMan** [comment]
Hmm. You're right. That PR merge was unwarranted.

**Comment by rugk** [comment]
Oh, really? /cc @bitbeans

So might you consider reopening this issue?

**Comment by BanzaiMan** [comment]
#925 has been reopened. This is a duplicate.
