### ISSUE TITLE
texlive-lang-chinese in whitelist, but causes error on travis.ci

### ISSUE THREAD

**Issue by michaelpacer** [travis-ci/apt-package-whitelist#3345]
When trying to install the package `texlive-lang-chinese` with the addons.apt.packages configuration, the build fails to find this addon. See this build: https://travis-ci.org/michaelpacer/travis_repo/jobs/160335257

It is included in the whitelist at https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise#L11884.

**Comment by BanzaiMan** [comment]
Most likely you are missing a source for this package. Please read https://docs.travis-ci.com/user/installing-dependencies#Identifying-the-source-for-a-missing-package.
