### ISSUE TITLE
APT whitelist request for mpich2

### ISSUE THREAD

**Issue by GiovanniBussi** [travis-ci/apt-package-whitelist#339]

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 libmpich-dev libmpich12 libmpich2-dev mpich mpich-doc mpich2 mpich2-doc libmpl-dev libmpl1 libopa-dev libopa1

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72398481.

**Comment by BanzaiMan** [comment]
See #406
