### ISSUE TITLE
APT whitelist request for gcc-mingw-w64-i686, binutils-mingw-w64-i686, mingw-w64-dev, wine

### ISSUE THREAD

**Issue by crowning-** [travis-ci/apt-package-whitelist#3482]
See https://travis-ci.org/dashpay/dash/jobs/173071266 and https://travis-ci.org/crowning-/dash/jobs/173384008

The commit before built without problems.

**Comment by BanzaiMan** [comment]
Sorry, but this doesn't fit the form described in README. Please split requests into individual packages.

I'm closing this.
