### ISSUE TITLE
APT whitelist request for libleveldb-dev

### ISSUE THREAD

**Issue by raylu-stripe** [travis-ci/apt-package-whitelist#3497]
This is in precise but not [trusty](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty)

**Comment by raylu-stripe** [comment]
Thanks for looking into this so far! The merged PR doesn't include libleveldb-dev, without which I cannot build bindings for other languages (plyvel for python3, in particular).

**Comment by BanzaiMan** [comment]
The PR doesn't contain it because `liblevedb-dev` was added long time ago https://github.com/travis-ci/apt-package-whitelist/commit/af49523a.

**Comment by raylu-stripe** [comment]
Oh, sorry. I didn't realize the PR was also for precise. I was looking for these to be included in trusty.
