### ISSUE TITLE
APT whitelist request for libnss3-dev

### ISSUE THREAD

**Issue by mcr** [travis-ci/apt-package-whitelist#354]

**Comment by BanzaiMan** [comment]
Duplicate of https://github.com/travis-ci/travis-ci/issues/4485.

**Comment by BanzaiMan** [comment]
Reopening to test the automation.

**Comment by BanzaiMan** [comment]
Failed to create a commit and a PR. This usually means that there has been a commit that resolved this request.
Inparticular, check https://github.com/travis-ci/apt-package-whitelist/commit/8e49b097
