### ISSUE TITLE
APT whitelist request for shellcheck

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/apt-package-whitelist#362]
This replaces travis-ci/travis-ci#3684.

The original text by @Maijin follows

------

`shellcheck` is able to detect possible errors in BashScript as well as warning about potential problems

**Comment by BanzaiMan** [comment]
@Maijin

So, this one is available from a whitelisted source:

https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545300#L218

`Adding {"alias"=>"debian-sid", "sourceline"=>"deb http://ftp.us.debian.org/debian unstable main contrib non-free", "key_url"=>"https://ftp-master.debian.org/keys/archive-key-7.0.asc"}`

Do you want to have this?

**Comment by Maijin** [comment]
Should be fine yes :+1:

**Comment by deivid-rodriguez** [comment]
Hi! So is this is not ready yet or do we need to use a different configuration?
