### ISSUE TITLE
APT whitelist request for texlive-base, texlive-latex-base, texlive-latex-extra, texlive-fonts-recommended, texlive-latex-recommended, latex-beamer, pandoc in TRUSTY

### ISSUE THREAD

**Issue by Falkor** [travis-ci/apt-package-whitelist#3629]
Note: These packages are allowed in precise. 

Anyway, the inconsistency between the precise and trusty whitelist should probably be corrected -- if packages were allowed on precise and also exist on trusty, why not importing them directly ?

Thanks!

**Comment by grooverdan** [comment]
There was a version check as part of the process - https://github.com/travis-ci/apt-package-whitelist/commit/d434145089f9195e7a78b45db2e298863ac54f2b. They may not have match in the versions.

Packages only get automaticly tested if there is a single package name (see the labels on other issues). The automated process doe pull in dependencies of the package listed and white lists those also. So write/edit this issue title to have a single package name as per official guidance. It will make the process quicker for you. If more packages are listed create separate issues.

(I'm not a travis official - just trying to help out based on observations).

**Comment by Falkor** [comment]
thanks @grooverdan, I should have paid more attention. 
I just created separate issues - #3756 #3757 #3758 #3759 #3760 #3761 #3762
