### ISSUE TITLE
APT whitelist request for a list of packages on trusty.

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/apt-package-whitelist#364]
This replaces travis-ci/travis-ci#3734.

The original text by @lekshmideepu follows

---

I would like to have the following list of packages for trusty: (sorry for the long list..)

ipython3, original-awk, autoremove, indent, python-debian, python-matplotlib, python-tk, python-coverage, python-setuptools, python-mpi4py, openmpi-doc, python3-all-dev, python3-numpy, python3-scipy, python3-nose, cython, libghc-readline-dev, python-django, python-django-tagging, python-svn, git-svn, python-cheetah, python-jinja2, python-mock, python-tk, python-gmpy, python-imaging-tk, cvs e2fsprogs gettext libpackagekit-glib2-dev groff libssh2-1-dev python-libssh2 slang-gsl libncurses5-dev check, cppcheck, vera++

**Comment by BanzaiMan** [comment]
`a list of packages on trusty.` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by lekshmideepu** [comment]
Sorry for the ambiguity in my request. I have read the package approval process and will do like the same in future. Thanks for your time!

**Comment by meatballhat** [comment]
Closed via #4205
