### ISSUE TITLE
APT whitelist request for more recent SQLite 3 version

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/apt-package-whitelist#368]
This replaces travis-ci/travis-ci#3815.

The original text by @waltaskew follows

------

I'm using features of sqlite3 which are not present in the version provided by the current `sqlite3` package in the whitelist:
https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise#L5609

I'd appreciate if I could request a version of sqlite >= 3.7.11 as that is the first version which supports bulk insert statements.
Maybe we could add an sqlite3-8 package to the whitelist?

Thanks!

**Comment by BanzaiMan** [comment]
`more recent SQLite 3 version` does not appear to a package name on which our automation process can handle.

APT packag request should be made for exactly one package, according to the form specified in
https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

If the source package of your requested package contains other related packages, you do not
have to open another one for those.
(When in doubt, do.)

**Comment by natemcmaster** [comment]
Can we add this package from ppa travis-ci/sqlite3?

sqlite3, version 3.7.15.1-1~travis1

https://launchpad.net/~travis-ci/+archive/ubuntu/sqlite3

**Comment by boblail** [comment]
+1

I'm also having to do this in my travis.yml:

    before_install:
      # The default version of sqlite on travis doesn't support bulk inserts.
      - sudo apt-add-repository -y ppa:travis-ci/sqlite3
      - sudo apt-get -y update
      - sudo apt-get -y install sqlite3=3.7.15.1-1~travis1

When I'd rather be able to do something like:

    sudo: false
    addons:
      apt:
        sources:
          - travis-ci/sqlite3
        packages:
          - sqlite3.7.15.1-1~travis1

**Comment by yangacer** [comment]
+1

**Comment by sgrif** [comment]
Unsure if there is a way to get attention on this by a human. There does not appear to be any automated process documented for simply updating the version of a package which is already whitelisted. The version of SQLite which Travis currently installs is now 5 years old, and there appears to be no way to get something more recent without abandoning the container infrastructure entirely.

**Comment by BanzaiMan** [comment]
I've [added the PPA source for SQLite3](https://github.com/travis-ci/apt-source-whitelist/commit/83fe91da3a96e37ae88d9ca0b3d77d34aafe0c6e).

```yaml
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
```

now updates SQLite3 to 3.7.15. https://travis-ci.org/BanzaiMan/travis_production_test/builds/117038832#L371

I'm closing this now.

**Comment by sferik** [comment]
:tada:
