### ISSUE TITLE
APT whitelist request for python-swiftclient

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/apt-package-whitelist#374]
This replaces travis-ci/travis-ci#3966.

The original text by @kahing follows

------

Needed to run SwiftProxy tests:

https://travis-ci.org/bouncestorage/swiftproxy/builds/64131426

**Comment by kahing** [comment]
I am still not able to install python-swiftclient on travis:

https://travis-ci.org/bouncestorage/swiftproxy/builds/75179136 :
```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install python-pip python-virtualenv python-dev libffi-dev python-swiftclient

Reading package lists...

Building dependency tree...

Reading state information...

E: Unable to locate package python-swiftclient
```
