### ISSUE TITLE
APT whitelist request for shellcheck

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/apt-package-whitelist#376]
This replaces travis-ci/travis-ci#4105.

The original text by @cep21 follows

------

Shellcheck is a great tool for integration/unit testing https://github.com/koalaman/shellcheck

**Comment by D0han** [comment]
It was working, I was using shellcheck as you can see here: https://travis-ci.org/D0han/mockmaker/builds/91283587#L211

Can i now still use it with no sudo?

**Comment by jimhester** [comment]
@BanzaiMan it was working fine with precise, as @D0han says, see https://travis-ci.org/Bioconductor/BBS/builds/91467371#L170-L184 for another example.

I think this was removed in error?

**Comment by D0han** [comment]
@jimhester if you need workaround, there it is:
```
sudo: required
dist: trusty

before_install:
    - echo "deb http://archive.ubuntu.com/ubuntu/ wily universe" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -q
    - sudo apt-get install shellcheck -y
```

**Comment by zbeekman** [comment]
The issue with precise seems to be that shell check has been removed from the package manager. If it doesn't work on Travis-CI container builds that is because it doesn't work on any precise machine, even with sudo, etc.

**Comment by ljharb** [comment]
So there's no way at all to run shellcheck on precise??

**Comment by brujoand** [comment]
You could just build it - > https://github.com/brujoand/sbp/blob/master/bin/bootstrap

**Comment by ljharb** [comment]
I did get v0.3.7 installed with https://github.com/travis-ci/apt-package-whitelist/issues/376#issuecomment-162922005, but I need v0.4.4 :-/

**Comment by brujoand** [comment]
@ljharb the approach I just posted installs v0.4.4

**Comment by ljharb** [comment]
@brujoand thanks, that works, but it's exceedingly slow :-/ it took 9 minutes where the previous one took 49 seconds. Any tips on making it faster?

**Comment by brujoand** [comment]
@ljharb ah, yeah I forgot to mention. You should really cache the ```.stack``` folder. First build takes ~10min the rest are down to a minute. It's done in the travis.yml --> https://github.com/brujoand/sbp/blob/development/.travis.yml#L6

**Comment by ljharb** [comment]
Thanks, I'll give that a shot.

**Comment by whymarrh** [comment]
An alternative to building Shellcheck on Precise: koalaman/shellcheck#589

```yml
addons:
    apt:
        sources:
            - debian-sid
        packages:
            - shellcheck
```

**Comment by zbeekman** [comment]
That didn't work last I tried
