### ISSUE TITLE
Package consistency between precise and trusty whitelist

### ISSUE THREAD

**Issue by Falkor** [travis-ci/apt-package-whitelist#3763]
Hi, 

To help a quick and easy migration of tests between Ubuntu [`precise`](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) and [`trusty`](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty), it would be great to see a better consistency between the respective whitelists -- after all, if packages were allowed on precise and also exist with the same name on trusty, why not importing them directly ?

**Comment by rdebath** [comment]
Creeping featuritis.

Long version...

Many packages suffer from requests for "this would be a neat feature, shirley it would be easy to add".
Often they do look easy to add ... at first ... so they get added, brokenly (at first). New features require new code, new code will probably use more of the system and eventually will run into a security barrier. You do NOT want new, broken code mediating your security and nor do Travis.

Oh, and don't call me "Shirley".  :wink:

**Comment by BanzaiMan** [comment]
It would be great if all Precise packages were able to be installed on Trusty without a problem and that the packages are created consistently across *all* package repositories.

Alas, we are not living in that utopia.

As it stands, we would like to run test on each package. I know this is tedious, but under the circumstances it is for the best. I am hopeful that, one day, we would not need these lists to use the `apt` addon.

I'm closing this.
