### ISSUE TITLE
APT whitelist request for mongodb-org-server

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/apt-package-whitelist#381]
This replaces travis-ci/travis-ci#4214.

The original text by @wbthomason follows

------

From http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/dist/10gen/binary-amd64/.
The source is already permitted (alias 'mongodb-upstart') but the package is not yet in the whitelist; only mongodb-10gen is. Thanks!

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for mongodb-org-server does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545424.

**Comment by fauvel** [comment]
@BanzaiMan The apt-source is white-listed now: `mongodb-upstart`. I've created a duplicate with #516, sorry about that!

**Comment by BanzaiMan** [comment]
This is superseded by the same request, #516.
