### ISSUE TITLE
Travisbot bug

### ISSUE THREAD

**Issue by rdebath** [travis-ci/apt-package-whitelist#3901]
Issue #3766 has been incorrectly processed by Travisbot.

1. The package source is gcc-defaults in the main archive.
2. It can already be installed by installing the whitelisted `g++-multilib` package

This means that it should already be whitelisted as it's a dependency of `g++-multilib` generated from the same source package!

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/apt-package-whitelist/issues/3766#issuecomment-270176701 about the source package issue with `gcc-defaults`.

We do not allow dependencies with the `apt` addon at this time. So the second issue is not valid.

I'm closing this for now.
