### ISSUE TITLE
APT whitelist request for opencv 3.2 in precise

### ISSUE THREAD

**Issue by walchko** [travis-ci/apt-package-whitelist#3951]
Unfortunately opencv 2.4 is only available and 3.2 is the current version. The github rep is [here](https://github.com/opencv/opencv) with the current release being [3.2](https://github.com/opencv/opencv/releases/tag/3.2.0). Our tests, which rely on the current version of the library, keep failing with the old version.

**Comment by BanzaiMan** [comment]
Sorry, but the `apt` addon is for apt packages. The official repository doesn't have any `opencv` package, so you'll have to find a source that does.
