### ISSUE TITLE
ubuntu-trusty: APT whitelist request for libnetfilter-queue-dev, iptables-dev

### ISSUE THREAD

**Issue by furusiyya** [travis-ci/apt-package-whitelist#4039]
Packages:  libnetfilter-queue-dev>=1.0.0 and iptables-dev are used in [Freki](https://github.com/kung-foo/freki).  
```ubuntu-precise``` whitelist have these packages which are outdated now.

**Comment by BanzaiMan** [comment]
Please follow the steps given in https://github.com/travis-ci/apt-package-whitelist#package-approval-process
