### ISSUE TITLE
APT whitelist request for python-epydoc in trusty

### ISSUE THREAD

**Issue by peterjc** [travis-ci/apt-package-whitelist#4200]
This was added for precise via #1523 / #1526

**Comment by mbrukman** [comment]
Please update your issue title: it should be called "[...] **in** trusty" not "[...] on trusty" as per [the template](https://github.com/travis-ci/apt-package-whitelist#package-approval-process); this is why it hasn't been reviewed / acted on by the automated system.

**Comment by peterjc** [comment]
Thanks for the tip - I never noticed that subtlety. Is there any reason not to use a GitHub issue template to guide people more directly?
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by mbrukman** [comment]
I'm not an owner of this repo, so I can't help with this, but they do have a link that does the equivalent of this in that section: the link behind the text "this repo" (not very obvious) points to the URL:

> https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___+in+_PRECISE_OR_TRUSTY_

which effectively does what you're suggesting.

Also, they probably want to have multiple types of issues on this repo, where submitting a new package for whitelisting is just one of the use cases, and having a single template would mean that everyone would get that as a template to start their issue, and some would be confused into using it when it wasn't applicable.

**Comment by peterjc** [comment]
Fair point. Anyway, thank you - the bot has been triggered now 👍

**Comment by BanzaiMan** [comment]
See travis-ci/apt-package-whitelist@5761eccc.
