### ISSUE TITLE
APT whitelist request for gcc-7 in trusty

### ISSUE THREAD

**Issue by verri** [travis-ci/apt-package-whitelist#4209]

**Comment by Morwenn** [comment]
As far as I can tell, you can already use GCC 7.1 from ubuntu-toolchain-r-test on Trusty. I already do that.

**Comment by verri** [comment]
@Morwenn I had tried a while ago, but it didn't work. Do you have a public `.travis.yml` I can check?

**Comment by Morwenn** [comment]
Sure, here you go: https://github.com/Morwenn/cpp-sort/blob/c%2B%2B17/.travis.yml

It's currently marked `sudo: required` because I'm trying to get Clang 5 to work again until llvm-toolchain-trusty-5.0 is allowed, but it isn't required for GCC 7.

**Comment by verri** [comment]
Thank you!
