### ISSUE TITLE
APT whitelist request for libvips-dev

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/apt-package-whitelist#425]
This replaces travis-ci/travis-ci#4398.

The original text by @gasi follows

------

This is needed to build the Node.js image library `sharp` which uses VIPS: https://github.com/lovell/sharp/

#### Script
```
before_install:
  - echo "Installing libvips..."
  - sudo add-apt-repository -y ppa:lovell/precise-backport-vips
  - sudo apt-get update
  - sudo apt-get install -y libvips-dev
```

See: https://github.com/lovell/sharp/issues/187#issuecomment-121789796

/cc @lovell

**Comment by gasi** [comment]
Thanks, @BanzaiMan. Unfortunately, this didn’t let me compile [`sharp`](https://github.com/lovell/sharp) as `vips.pc` is not in the `PKG_CONFIG_PATH`. Do you know where it’s installed in?

```
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
gyp: Call to 'PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 1. while trying to load binding.gyp
```

/cc @lovell

**Comment by lovell** [comment]
@gasi This commit for this issue allows `libvips-dev` [v7.26.3](http://packages.ubuntu.com/precise/libvips-dev) to be installed via [addons.apt.packages](http://docs.travis-ci.com/user/apt/). For v7.40.6 we require https://github.com/travis-ci/apt-source-whitelist/issues/68 to also allow `ppa:lovell/precise-backport-vips` in `addons.apt.sources`.

**Comment by gasi** [comment]
:+1:
