### ISSUE TITLE
APT whitelist request for botan1.10

### ISSUE THREAD

**Issue by DavidKeller** [travis-ci/apt-package-whitelist#446]
http://packages.ubuntu.com/precise/libbotan-1.10-0

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for libbotan does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545699.

**Comment by BanzaiMan** [comment]
Ah, the source package is `libbotan-1.10`.

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for libbotan-1.10 does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72555036.

**Comment by BanzaiMan** [comment]
Ran tests, but could not found source package. Either the source package for botan-1.10 does not exist, or the package needs an APT source. If you wisht to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72555564.

**Comment by DavidKeller** [comment]
Hi BanzaiMan, almost :-)

Source package is ```botan1.10```

http://packages.ubuntu.com/source/precise/botan1.10

**Comment by BanzaiMan** [comment]
Ran tests and found setuid bits by purely textual search. Further analysis is required.

If these are found to be benign, add:

 botan1.10-dbg libbotan-1.10-0 libbotan1.10-dev

 See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72599252.
