### ISSUE TITLE
APT whitelist request for python3-pip

### ISSUE THREAD

**Issue by rmcgibbo** [travis-ci/apt-package-whitelist#768]

**Comment by fwalch** [comment]
FYI, just wanted to request this, and found out this package doesn't exist in Ubuntu precise. You might be able to use `easy_install3` instead (#771).

**Comment by rmcgibbo** [comment]
Oh cool call. I'll close this then.

**Comment by gijzelaerr** [comment]
trusty does have this package, and I would like to request to whitelist this package. I don't always want to use the python images but the generic image and run tests with the distro python/pip. Same for python-pip

**Comment by Snaipe** [comment]
Please reopen this. The package exists in trusty and should be the recommended way to get pip3 on the system.

(paging @BanzaiMan since he seems to be the main maintainer of this project)

**Comment by BanzaiMan** [comment]
APT package addon is not designed to work with Trusty. You can use `sudo` there.

**Comment by Snaipe** [comment]
@BanzaiMan Sorry, I meant precise, not trusty.

**Comment by BanzaiMan** [comment]
Which source is supposed to have this? http://packages.ubuntu.com/precise/python3-pip

**Comment by Snaipe** [comment]
Mmh, I think I must have made a mistake when searching for the package. Nevermind, sorry for highlighting you for nothing.

**Comment by BanzaiMan** [comment]
@Snaipe No worries.
